language: generic
sudo: required
services:
  - docker

# Build docker image
before_install:
  - docker build -t shabbirsaifee/docker-react-aws -f Dockerfile.dev .

# Run the tests
script:
  - docker run -e CI=true shabbirsaifee/docker-react-aws npm run test -- --coverage

# automatic deploy to aws elastic beanstalk
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-aws"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-772331254898"
  bucket_path: "docker-react-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
